route:
  receiver: "webhook-receiver"
  group_wait: 5s # espera 5s agrupando alertas parecidos antes de mandar
  group_interval: 10s
  repeat_interval: 1m # se o alerta continuar ativo, reenvia a cada 1min

receivers:
  - name: "webhook-receiver"
    webhook_configs:
      - url: "http://webhook-receiver:8001/webhook"
        send_resolved: true # também avisa quando o alerta é resolvido
