"""
dashboard — Phase 6.

Visual interface for the human-in-the-loop flow. Consumes the same
agent-orchestrator endpoints:
  - GET  /pending               -> incidents awaiting approval
  - POST /approve/{thread_id}   -> approve/reject
  - GET  /incidents             -> already concluded incidents
"""
import os

import httpx
import streamlit as st
from streamlit_autorefresh import st_autorefresh

AGENT_ORCHESTRATOR_URL = os.environ.get("AGENT_ORCHESTRATOR_URL", "http://agent-orchestrator:8001")

st.set_page_config(page_title="Incident Copilot", layout="wide")

# Auto-refreshes the whole page every 5s — so new incidents (or
# automatic resolutions) show up without clicking anything. A fixed
# `key` prevents Streamlit from recreating the component from scratch
# on every rerun.
st_autorefresh(interval=5000, key="auto_refresh_incidents")


def _get(path: str) -> dict | None:
    try:
        response = httpx.get(f"{AGENT_ORCHESTRATOR_URL}{path}", timeout=10)
        response.raise_for_status()
        return response.json()
    except Exception as e:
        st.error(f"Could not reach the agent-orchestrator ({path}): {e}")
        return None


def _approve(thread_id: str, approved: bool) -> None:
    try:
        response = httpx.post(
            f"{AGENT_ORCHESTRATOR_URL}/approve/{thread_id}",
            json={"approved": approved},
            timeout=30,
        )
        response.raise_for_status()
    except Exception as e:
        st.error(f"Failed to send decision: {e}")


def _severity_component(severity: str):
    """Picks the Streamlit visual component based on severity — a
    simple way to add visual emphasis without custom CSS."""
    mapping = {
        "critical": st.error,
        "high": st.error,
        "medium": st.warning,
        "low": st.info,
    }
    return mapping.get((severity or "").lower(), st.info)


st.title("🚨 Incident Copilot — Approval Dashboard")
st.caption(
    "Diagnoses generated by AI agents (LangGraph + RAG) awaiting human "
    "review before any corrective action is executed. "
    "Auto-refreshes every 5s."
)

pending_resp = _get("/pending")
pending = (pending_resp or {}).get("pendentes", {})

processing_resp = _get("/processing")
processing = (processing_resp or {}).get("processando", {})

incidents_resp = _get("/incidents")
incidents = (incidents_resp or {}).get("incidentes", {})

# Left column (wider) for what needs human attention NOW; right column
# (narrower) for history, which is just for reference.
col_pending, col_completed = st.columns([2, 1])

with col_pending:
    st.header("Awaiting human action")

    if not pending and not processing:
        st.success("No incidents in progress right now.")

    # "Processing" first — it's the most recent/urgent to keep an eye
    # on, since the diagnosis is still being generated.
    for thread_id, info in processing.items():
        with st.container(border=True):
            st.subheader(info.get("alert_summary", "Alert with no summary"))
            st.info("🧠 Analyzing the incident... (searching runbooks and querying the LLM)")
            st.caption(f"thread_id: `{thread_id}`")

    for thread_id, incident in pending.items():
        with st.container(border=True):
            st.subheader(incident.get("alert_summary", "Alert with no summary"))

            col_info, col_action = st.columns([3, 1])

            with col_info:
                st.markdown(f"**Diagnosis:** {incident.get('diagnosis')}")
                st.markdown(f"**Recommended action:** {incident.get('recommended_action')}")

                severity = incident.get("severity_assessed", "unknown")
                _severity_component(severity)(f"Severity assessed by the agent: **{severity}**")

                action_type = incident.get("action_type")
                target = incident.get("target_container")
                if action_type == "restart_container":
                    st.markdown(f"⚙️ Automatable action: **restart container `{target}`**")
                else:
                    st.markdown("⚙️ **Not** automatable — requires manual intervention even if approved")

                st.caption(f"thread_id: `{thread_id}`")

            with col_action:
                if st.button("✅ Approve", key=f"approve_{thread_id}", use_container_width=True):
                    _approve(thread_id, True)
                    st.rerun()
                if st.button("❌ Reject", key=f"reject_{thread_id}", use_container_width=True):
                    _approve(thread_id, False)
                    st.rerun()

with col_completed:
    st.header("Completed")

    if not incidents:
        st.caption("No completed incidents yet.")
    else:
        for thread_id, incident in reversed(list(incidents.items())):
            approved = incident.get("approved")
            auto_resolved = incident.get("auto_resolved")
            if auto_resolved:
                icon = "⏱️"
            elif approved:
                icon = "✅"
            else:
                icon = "❌"

            short_diagnosis = (incident.get("diagnosis") or "No diagnosis")[:60]
            with st.expander(f"{icon} {short_diagnosis}..."):
                st.markdown(f"**Diagnosis:** {incident.get('diagnosis')}")
                st.markdown(f"**Recommended action:** {incident.get('recommended_action')}")
                if auto_resolved:
                    st.markdown("**Auto-resolved** — nobody approved/rejected it in time")
                else:
                    st.markdown(f"**Approved:** {'Yes' if approved else 'No'}")
                st.markdown(f"**Action result:** {incident.get('action_result')}")
                st.caption(f"thread_id: `{thread_id}`")
